import type { AppState } from './types';

export const initialState: AppState = {
  familyMembers: [
    { id: 'steven', name: 'Steven', avatar: '👨', role: 'parent' },
    { id: 'sarah', name: 'Sarah', avatar: '👩', role: 'parent' },
    { id: 'liam', name: 'Liam', avatar: '👦', role: 'child' },
    { id: 'jack', name: 'Jack', avatar: '🧒', role: 'child' },
    { id: 'alfie', name: 'Alfie', avatar: '👦', role: 'child' },
    { id: 'noah', name: 'Noah', avatar: '🧒', role: 'child' },
    { id: 'ethan', name: 'Ethan', avatar: '👦', role: 'child' },
  ],
  events: [
    {
      id: 'e1',
      title: 'Rugby Training',
      memberId: 'jack',
      date: 'Saturday',
      time: '09:30',
      location: 'The Park',
      sport: 'rugby',
      transportAssigned: false,
      kitChecked: false,
    },
    {
      id: 'e2',
      title: 'Football Match',
      memberId: 'alfie',
      date: 'Saturday',
      time: '11:00',
      location: 'Riverside Ground',
      sport: 'football',
      transportAssigned: false,
      kitChecked: true,
    },
    {
      id: 'e3',
      title: 'Swimming Lesson',
      memberId: 'noah',
      date: 'Sunday',
      time: '10:00',
      location: 'Leisure Centre',
      sport: 'swimming',
      transportAssigned: true,
      kitChecked: true,
    },
    {
      id: 'e4',
      title: 'Football Training',
      memberId: 'liam',
      date: 'Saturday',
      time: '14:00',
      location: 'Sports Park',
      sport: 'football',
      transportAssigned: true,
      kitChecked: false,
    },
  ],
  drivers: [
    { id: 'd1', name: 'Steven', seats: 4, passengers: ['liam', 'noah'] },
    { id: 'd2', name: 'Sarah', seats: 3, passengers: ['ethan'] },
    { id: 'd3', name: 'Grandad Mike', seats: 4, passengers: [] },
  ],
  liftRequests: [
    {
      id: 'lr1',
      childId: 'alfie',
      childName: 'Alfie',
      eventId: 'e2',
      eventTitle: 'Football Match',
      time: '11:00',
      location: 'Riverside Ground',
      assignedDriverId: null,
    },
    {
      id: 'lr2',
      childId: 'jack',
      childName: 'Jack',
      eventId: 'e1',
      eventTitle: 'Rugby Training',
      time: '09:30',
      location: 'The Park',
      assignedDriverId: null,
    },
    {
      id: 'lr3',
      childId: 'liam',
      childName: 'Liam',
      eventId: 'e4',
      eventTitle: 'Football Training',
      time: '14:00',
      location: 'Sports Park',
      assignedDriverId: 'd1',
    },
    {
      id: 'lr4',
      childId: 'noah',
      childName: 'Noah',
      eventId: 'e3',
      eventTitle: 'Swimming Lesson',
      time: '10:00',
      location: 'Leisure Centre',
      assignedDriverId: 'd1',
    },
  ],
  kitItems: [
    { id: 'k1', name: 'Rugby boots', memberId: 'jack', memberName: 'Jack', sport: 'rugby', urgent: true, completed: false, category: 'boots' },
    { id: 'k2', name: 'Gum shield', memberId: 'jack', memberName: 'Jack', sport: 'rugby', urgent: true, completed: false, category: 'protection' },
    { id: 'k3', name: 'Rugby jersey', memberId: 'jack', memberName: 'Jack', sport: 'rugby', urgent: false, completed: true, category: 'clothing' },
    { id: 'k4', name: 'Football boots', memberId: 'alfie', memberName: 'Alfie', sport: 'football', urgent: false, completed: true, category: 'boots' },
    { id: 'k5', name: 'Shin pads', memberId: 'alfie', memberName: 'Alfie', sport: 'football', urgent: false, completed: true, category: 'protection' },
    { id: 'k6', name: 'Water bottle', memberId: 'liam', memberName: 'Liam', sport: 'football', urgent: false, completed: false, category: 'accessories' },
    { id: 'k7', name: 'Swimming goggles', memberId: 'noah', memberName: 'Noah', sport: 'swimming', urgent: false, completed: true, category: 'accessories' },
    { id: 'k8', name: 'Swim cap', memberId: 'noah', memberName: 'Noah', sport: 'swimming', urgent: false, completed: false, category: 'accessories' },
    { id: 'k9', name: 'Kit bag', memberId: 'jack', memberName: 'Jack', sport: 'rugby', urgent: false, completed: false, category: 'bag' },
  ],
  notices: [
    {
      id: 'n1',
      from: 'Sarah',
      title: 'Tournament this Saturday!',
      body: 'Reminder: Jack\'s rugby tournament starts at 9am sharp. All players must be there by 8:45. Bring extra snacks and warm layers — it might be chilly.',
      timestamp: '2h ago',
      urgent: true,
      read: false,
      category: 'match',
    },
    {
      id: 'n2',
      from: 'Coach Dave',
      title: 'Training moved to 10am',
      body: 'Due to ground maintenance, Saturday\'s football training has moved from 9am to 10am at the usual pitch.',
      timestamp: '5h ago',
      urgent: false,
      read: true,
      category: 'training',
    },
    {
      id: 'n3',
      from: 'Club Admin',
      title: 'Subs due by Friday',
      body: 'Monthly subs are due by Friday. Please pay via the club app or bring cash to training.',
      timestamp: '1d ago',
      urgent: false,
      read: true,
      category: 'admin',
    },
  ],
  shoppingItems: [
    { id: 's1', name: 'Rugby boots (size 5)', memberId: 'jack', memberName: 'Jack', urgent: true, purchased: false },
    { id: 's2', name: 'Gum shield', memberId: 'jack', memberName: 'Jack', urgent: true, purchased: false },
    { id: 's3', name: 'Water bottle', memberId: 'liam', memberName: 'Liam', urgent: false, purchased: false },
    { id: 's4', name: 'Swim cap (blue)', memberId: 'noah', memberName: 'Noah', urgent: false, purchased: false },
    { id: 's5', name: 'Football socks', memberId: 'alfie', memberName: 'Alfie', urgent: false, purchased: true },
  ],
  chores: [
    { id: 'c1', title: 'Pack rugby kit bag', assignedTo: 'jack', assignedName: 'Jack', points: 10, completed: false, dueDate: 'Friday' },
    { id: 'c2', title: 'Check all boots are clean', assignedTo: 'liam', assignedName: 'Liam', points: 5, completed: true, dueDate: 'Thursday' },
    { id: 'c3', title: 'Wash football kit', assignedTo: 'sarah', assignedName: 'Sarah', points: 10, completed: false, dueDate: 'Friday' },
    { id: 'c4', title: 'Print match schedule', assignedTo: 'steven', assignedName: 'Steven', points: 5, completed: true, dueDate: 'Thursday' },
    { id: 'c5', title: 'Prepare snack bag', assignedTo: 'alfie', assignedName: 'Alfie', points: 5, completed: false, dueDate: 'Saturday' },
  ],
  badges: [
    { id: 'b1', name: 'Kit Hero', description: 'Completed all kit tasks', icon: '⚽', earned: false },
    { id: 'b2', name: 'Lift Legend', description: 'Helped with transport', icon: '🚗', earned: true, earnedBy: 'Steven' },
    { id: 'b3', name: 'Tournament Ready', description: 'Completed weekend checklist', icon: '🏆', earned: false },
    { id: 'b4', name: 'Streak Starter', description: '3 days ready in a row', icon: '🔥', earned: false },
    { id: 'b5', name: 'Early Bird', description: 'Ready before 8am', icon: '🌅', earned: true, earnedBy: 'Sarah' },
  ],
  weather: {
    condition: 'rain',
    temp: 12,
    description: 'Rain expected Saturday morning',
  },
};
